name: chat_qr
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf_router:
  shelf:
  shelf_web_socket:
  mysql_client:
  http:
  googleapis_auth: ^1.3.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
